version: "3.7"
services:

## --------------------------- API SCRAPING CARS --------------------------- ##

  car_scraping_api:
    build: . ## Build local da imagem
    container_name: car_scraping_api ## Nome do container
    
    networks:
      - jnunesfiorimnet ## Nome da rede interna
    
    environment:
      ## 🌐 Configurações da API
      - NODE_ENV=production
      - PORT=3000
      - TZ=America/Sao_Paulo
      
      ## 🔒 Configurações de Segurança
      - CORS_ORIGIN=*
      - RATE_LIMIT_POINTS=10
      - RATE_LIMIT_DURATION=60
      
      ## 🚗 Configurações de Scraping
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
      - PUPPETEER_ARGS=--no-sandbox,--disable-setuid-sandbox,--disable-dev-shm-usage
      
      ## 📊 Configurações de Performance
      - MAX_REQUEST_SIZE=10mb
      - REQUEST_TIMEOUT=30000
      
    ports:
      - "3000:3000" ## Expor porta 3000 diretamente
    
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 2048M ## Mais memória para o Puppeteer
        reservations:
          cpus: "0.5"
          memory: 1024M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

## --------------------------- REDIS (OPCIONAL - PARA CACHE) --------------------------- ##

  redis_cache:
    image: redis:7-alpine ## Versão do Redis
    container_name: redis_cache_cars
    
    networks:
      - jnunesfiorimnet ## Nome da rede interna
    
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    
    volumes:
      - redis_cache_data:/data ## Volume para persistência
    
    environment:
      - TZ=America/Sao_Paulo
      
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

## --------------------------- VOLUMES --------------------------- ##

volumes:
  redis_cache_data: ## Volume para dados do Redis
    driver: local

## --------------------------- REDES --------------------------- ##

networks:
  jnunesfiorimnet: ## Nome da rede interna
    external: true
    name: jnunesfiorimnet ## Nome da rede interna
