version: '3.8'

services:
  car-scraping-api:
    build: .
    container_name: car-scraping-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    networks:
      - car-scraping-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.car-scraping.rule=Host(`api-seusite.com`)"
      - "traefik.http.routers.car-scraping.entrypoints=websecure"
      - "traefik.http.routers.car-scraping.tls.certresolver=letsencrypt"

networks:
  car-scraping-network:
    driver: bridge

volumes:
  logs:
  data:
